spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/appDB
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver

server:
  port: 7080
