spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/appDB
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 7080
